env:
    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: "1670106753"
    TG_TOKEN: ENCRYPTED[983bbf1090f7d681f2264c0b7e41d6c448cab2f353f5518567002535f7cf1d117a7ce8f998f5f52664d7a489d4c15aec]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "TWRP CI"
  timeout_in: 120m
  container:
      image: ghcr.io/tunbudi06/docker:arch
      cpu: 8
      memory: 32G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/Recoveries-CI/TWRP-CI/main/scripts/upload.sh)"
